// Images: Wikimedia Commons, used under their Creative Commons licenses.
// Photo fields come from each file's Commons page and EXIF data:
//   takenFrom – viewpoint or trek the photo was shot from (null if not recorded)
//   takenAt   – local camera time, ISO format; date-only or year when that's all there is
//   camera    – camera body and focal length, when the EXIF has them
//   coords    – [lat, lon] where the photo was taken, when known
const thumb = (path, width = 1920) =>
  `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}/${width}px-${path.split("/").pop()}`;

// x/y are percentages of the image width/height, at the top of each summit.
// Kumaon positions come from the image notes on the Commons file page.
export const panoramas = [
  {
    id: "garhwal",
    title: "Garhwal Himalaya",
    description:
      "From the summit of Chandrashila, above Tungnath, the view sweeps from the Gangotri peaks in the west across Kedarnath and Chaukhamba to Nanda Devi in the east. The peak names are marked on the photo itself.",
    labelled: true,
    image: thumb("b/b1/Chandrashila_Panorama.jpg", 3840),
    width: 13908,
    height: 2261,
    credit: "Drashokk",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=169841460",
    takenFrom: "Chandrashila summit, 5 km trek from Chopta, Rudraprayag",
    takenAt: "2013-10-25",
    camera: null,
    coords: [30.488056, 79.221389],
    peaks: [
      { name: "Bhagirathi", elevation: 6856, x: 18.6 },
      { name: "Gangotri", elevation: 6672, x: 23.7 },
      { name: "Kedarnath", elevation: 6940, x: 39.4 },
      { name: "Kedar Dome", elevation: 6831, x: 48.5 },
      { name: "Chaukhamba", elevation: 7138, x: 74.7 },
      { name: "Nanda Devi", elevation: 7816, x: 96.9 },
    ],
  },
  {
    id: "kumaon",
    title: "Kumaon Himalaya",
    description:
      "Seen from Ranikhet in Almora district, about 150 km of the main range lines the horizon, from Nanda Ghunti and Trisul past Nanda Devi and Nanda Kot to the five summits of Panchachuli.",
    labelled: false,
    image: thumb(
      "4/4d/Panorama_of_Himalayas_from_Ranikhet%2C_Uttarakhand%2C_India.jpg",
      3840,
    ),
    width: 7570,
    height: 2200,
    credit: "Harshit SR, edited by UnpetitproleX",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=173108278",
    takenFrom: "Ranikhet, Almora",
    takenAt: "2020-12-14T11:01",
    camera: null,
    coords: [29.65, 79.42],
    peaks: [
      { name: "Nanda Ghunti", elevation: 6309, x: 9.07, y: 23.3 },
      { name: "Trisul", elevation: 7120, x: 17.83, y: 18.5 },
      { name: "Mrigthuni", elevation: 6855, x: 25.73, y: 19.4 },
      { name: "Devtoli", elevation: 6788, x: 31.55, y: 21.1 },
      { name: "Nanda Devi", elevation: 7816, x: 35.05, y: 21.1 },
      { name: "Sunanda Devi", elevation: 7434, x: 37.48, y: 24.1 },
      { name: "Panwali Dwar", elevation: 6683, x: 38.99, y: 24.1 },
      { name: "Nanda Khat", elevation: 6611, x: 40.43, y: 25.0 },
      { name: "Changuch", elevation: 6322, x: 46.93, y: 26.3 },
      { name: "Nanda Kot", elevation: 6861, x: 50.5, y: 23.3 },
      { name: "Dangthal", elevation: 6050, x: 57.69, y: 26.3 },
      { name: "Rajrambha", elevation: 6537, x: 74.35, y: 28.0 },
      { name: "Panchachuli", elevation: 6904, x: 82.8, y: 25.0 },
    ],
  },
];

// Traveller fields:
//   summit      – [lat, lon] of the summit, from Wikipedia / Wikidata
//   seeFrom     – places a visitor can actually stand to see the peak
//   gettingThere, bestTime, permit – plain trip-planning notes
// Road distances are approximate; check local conditions before setting out.
export const mountains = [
  {
    name: "Nanda Devi",
    elevation: 7816,
    district: "Chamoli",
    region: "Garhwal Himalaya",
    summit: [30.375833, 79.970833],
    description:
      "The sanctuary around the peak has been closed to visitors since 1983, so you see Nanda Devi from the hill towns and treks around it. Munsiyari and Auli face it head-on.",
    seeFrom: ["Munsiyari", "Auli", "Kausani"],
    gettingThere:
      "Munsiyari is about 275 km by road from Kathgodam, the nearest railhead. Auli is 15 km above Joshimath, a full day's drive from Rishikesh.",
    bestTime: "Oct–Nov, Mar–May",
    permit: "None for viewpoints; the inner sanctuary is closed",
    image: thumb("d/d2/Mt._Nanda_Devi.jpg"),
    credit: "Sumod K Mohan",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=61657012",
    takenFrom: null,
    takenAt: "2016-12-18T08:00",
    camera: "Nikon D300S · 170 mm",
    coords: null,
  },
  {
    name: "Kamet",
    elevation: 7756,
    district: "Chamoli",
    region: "Zanskar Range",
    summit: [30.92, 79.591667],
    description:
      "Kamet stands in the restricted zone near the Tibet border, so most travellers see it from Auli or from the top of the Kuari Pass trek.",
    seeFrom: ["Auli", "Kuari Pass"],
    gettingThere:
      "Auli is 15 km by road above Joshimath. Kuari Pass is a 5–6 day trek that starts in the villages near Joshimath.",
    bestTime: "Oct–Nov, Mar–Apr",
    permit: "None for Auli; treks need a forest permit, usually arranged by the operator",
    image: thumb("c/c6/Kamet_Closeup.jpg"),
    credit: "Rohit Gosain",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=71194109",
    takenFrom: null,
    takenAt: "2017-12-23T09:56",
    camera: "Sony DSC-H400 · 178 mm",
    coords: null,
  },
  {
    name: "Sunanda Devi",
    elevation: 7434,
    district: "Chamoli",
    region: "Garhwal Himalaya",
    summit: [30.366667, 79.994444],
    description:
      "Also called Nanda Devi East. The closest you can get is Nanda Devi East Base Camp, a week-long trek from Munsiyari up the Gori Ganga valley.",
    seeFrom: ["Munsiyari", "Kausani"],
    gettingThere:
      "Munsiyari is about 275 km by road from Kathgodam. The base camp trek runs via Lilam, Bogdiyar and Martoli.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Inner Line Permit from the SDM office in Munsiyari for the base camp trek",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/76/Nanda_Devi_from_Kausani.JPG",
    credit: "Tribhuwan (en.wikipedia)",
    license: "Public domain",
    source: "https://commons.wikimedia.org/w/index.php?curid=26086448",
    takenFrom: "Kausani, Bageshwar",
    takenAt: "2006-11-20T10:50",
    camera: "Sony DCR-HC42E · 36 mm",
    coords: null,
  },
  {
    name: "Chaukhamba",
    elevation: 7138,
    district: "Uttarkashi / Chamoli",
    region: "Gangotri Group",
    summit: [30.749722, 79.291111],
    description:
      "One of the easiest big-peak views in Uttarakhand. Chaukhamba reflects in Deoria Tal, a short walk from the road, and fills the skyline from Chopta and Chandrashila.",
    seeFrom: ["Deoria Tal", "Chopta", "Chandrashila", "Madhyamaheshwar"],
    gettingThere:
      "Deoria Tal is a 2.5 km walk from Sari village near Ukhimath. Chandrashila is a 5 km climb from Chopta via Tungnath.",
    bestTime: "Oct–Nov, Mar–May",
    permit: "None",
    image: thumb("c/ce/Chaukhamba_at_Boodha_Madhyamaheshwar.jpg"),
    credit: "Abhishek.ghosh1984",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=49314980",
    takenFrom: "Boodha Madhyamaheshwar trek, Rudraprayag",
    takenAt: "2015-10-08T07:34",
    camera: "Nikon D7000 · 18 mm",
    coords: null,
  },
  {
    name: "Trisul",
    elevation: 7120,
    district: "Chamoli",
    region: "Garhwal Himalaya",
    summit: [30.312778, 79.777222],
    description:
      "Fills the sunrise view from Kausani and Ranikhet, and towers over the Brahmatal and Roopkund treks.",
    seeFrom: ["Kausani", "Ranikhet", "Brahmatal", "Bedni Bugyal"],
    gettingThere:
      "Kausani is about 130 km by road from Kathgodam. The Brahmatal and Roopkund treks start at Lohajung.",
    bestTime: "Oct–Nov, Mar–May; Brahmatal in Dec–Mar",
    permit: "None for Kausani; treks need a forest permit, usually arranged by the operator",
    image: thumb("6/6f/Time_lapse_shot_of_Trishul_peak.jpg"),
    credit: "Harshit SR",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=118822148",
    takenFrom: null,
    takenAt: "2021-11-25",
    camera: null,
    coords: null,
  },
  {
    name: "Kedarnath",
    elevation: 6940,
    district: "Rudraprayag / Uttarkashi",
    region: "Gangotri Group",
    summit: [30.795, 79.069444],
    description:
      "The peak stands right behind the Kedarnath temple, so every pilgrim sees it. For a closer look, hike on to Vasuki Tal.",
    seeFrom: ["Kedarnath Temple", "Vasuki Tal", "Chandrashila"],
    gettingThere:
      "Trek 16 km from Gaurikund (shared jeeps run up from Sonprayag), or take a helicopter from Phata or Guptkashi. Vasuki Tal is about 8 km beyond the temple.",
    bestTime: "May–Jun, Sep–Oct; the temple is open roughly May–Nov",
    permit: "Free Char Dham yatra registration, done online before you go",
    image: thumb("c/c8/Mt._Kedarnath.jpg"),
    credit: "Aditya Mandke",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=70945847",
    takenFrom: null,
    takenAt: "2016-04-20T06:02",
    camera: "Canon PowerShot SX50 HS · 108 mm",
    coords: null,
  },
  {
    name: "Panchachuli",
    elevation: 6904,
    district: "Pithoragarh",
    region: "Kumaon Himalaya",
    summit: [30.214167, 80.4275],
    description:
      "The five peaks line up directly across the valley from Munsiyari. Sunrise from the town or from Khaliya Top is the classic view.",
    seeFrom: ["Munsiyari", "Khaliya Top", "Chaukori"],
    gettingThere:
      "Munsiyari is about 275 km by road from Kathgodam. Panchachuli Base Camp is a trek up the Darma valley from Dugtu, reached via Dharchula.",
    bestTime: "Oct–Nov, Mar–May",
    permit: "Inner Line Permit from the SDM office in Dharchula for the Darma valley",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3c/Panchchuli_mountain_%2800307%29.JPG",
    credit: "Tribhuwan (en.wikipedia)",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=3852514",
    takenFrom: "Chaukori, Pithoragarh",
    takenAt: "2006-11-20T12:18",
    camera: "Sony DCR-HC42E · 12 mm",
    coords: null,
  },
  {
    name: "Nanda Kot",
    elevation: 6861,
    district: "Pithoragarh",
    region: "Kumaon Himalaya",
    summit: [30.281667, 80.068333],
    description:
      "A sharp snow pyramid that is easy to pick out on the skyline from Munsiyari and Chaukori.",
    seeFrom: ["Munsiyari", "Chaukori"],
    gettingThere:
      "Munsiyari is about 275 km by road from Kathgodam. Chaukori is on the way, near Berinag.",
    bestTime: "Oct–Nov, Mar–May",
    permit: "None for viewpoints",
    image: thumb("4/46/Nanda_Kot.jpg"),
    credit: "John Patton",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=10632592",
    takenFrom: null,
    takenAt: "1992",
    camera: null,
    coords: null,
  },
  {
    name: "Bhagirathi",
    elevation: 6856,
    district: "Uttarkashi",
    region: "Gangotri Group",
    summit: [30.84977, 79.14654],
    description:
      "The three Bhagirathi summits tower over Gaumukh, the glacier snout where the Ganga begins. You see them up close on the Gaumukh–Tapovan trek.",
    seeFrom: ["Bhojbasa", "Gaumukh", "Tapovan"],
    gettingThere:
      "Drive to Gangotri, about 260 km from Rishikesh, then trek 18 km to Gaumukh. Tapovan is another 4 km up, across the glacier.",
    bestTime: "May–Jun, Sep–Oct; the park is closed in winter",
    permit: "Gangotri National Park permit from the forest office in Uttarkashi; Gaumukh is capped at 150 visitors a day",
    image: thumb("4/4a/Bhagirathi_Massif.jpg"),
    credit: "DipankarSen68",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=89258148",
    takenFrom: "Kalindi Khal trek, Uttarkashi",
    takenAt: "2015-09-16T12:08",
    camera: "Canon IXUS 145 · 30 mm",
    coords: null,
  },
  {
    name: "Mrigthuni",
    elevation: 6855,
    district: "Bageshwar",
    region: "Kumaon Himalaya",
    summit: [30.29, 79.829722],
    description:
      "Best seen from Dhakuri, the first big viewpoint on the Pindari Glacier trek, lined up with Maiktoli and Devtoli.",
    seeFrom: ["Dhakuri", "Ranikhet"],
    gettingThere:
      "The Pindari trek starts at Kharkiya or Loharkhet, a short drive from Bageshwar. Dhakuri is the first pass on the trail.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb("e/ec/Mrigthuni.jpg"),
    credit: "Rohit Gosain",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=71194108",
    takenFrom: null,
    takenAt: "2017-12-23T09:25",
    camera: "Sony DSC-H400 · 210 mm",
    coords: null,
  },
  {
    name: "Kedar Dome",
    elevation: 6831,
    district: "Uttarkashi",
    region: "Gangotri Group",
    summit: [30.808611, 79.078889],
    description:
      "A broad snow dome next to Kedarnath peak. Trekkers see it from Tapovan on the Gangotri side, or from the trail above Vasuki Tal on the Kedarnath side.",
    seeFrom: ["Tapovan", "Vasuki Tal"],
    gettingThere:
      "Tapovan is 22 km from Gangotri via Gaumukh. Vasuki Tal is about 8 km beyond the Kedarnath temple.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Gangotri National Park permit for Tapovan; Char Dham registration for Kedarnath",
    image: thumb("1/1a/Kedardome_WTK20150918-DSC_4240.jpg"),
    credit: "schwiki",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=46916598",
    takenFrom: "Trail from Vasuki Tal to Khara Patthar",
    takenAt: "2015-09-18T09:06",
    camera: "Nikon D7000 · 48 mm",
    coords: null,
  },
  {
    name: "Devtoli",
    elevation: 6788,
    district: "Bageshwar",
    region: "Kumaon Himalaya",
    summit: [30.285833, 79.853333],
    description:
      "Seen side by side with Mrigthuni and Maiktoli from Dhakuri top on the Pindari Glacier trek.",
    seeFrom: ["Dhakuri", "Ranikhet"],
    gettingThere:
      "The Pindari trek starts at Kharkiya or Loharkhet, a short drive from Bageshwar. Dhakuri is the first pass on the trail.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb(
      "4/46/Mrigthuni%2C_Devtoli_annd_Maiktoli_from_Dhakuri_top.jpg",
    ),
    credit: "Goutam1962",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=89444276",
    takenFrom: "Dhakuri top, Pindari Glacier trek",
    takenAt: "2011-04-08T06:15",
    camera: "Canon EOS 550D · 55 mm",
    coords: null,
  },
  {
    name: "Panwali Dwar",
    elevation: 6683,
    district: "Bageshwar",
    region: "Kumaon Himalaya",
    summit: [30.289444, 79.955833],
    description:
      "Rises at the head of the Pindari valley. You walk towards it, with Nanda Khat beside it, for the last days of the Pindari Glacier trek.",
    seeFrom: ["Pindari Glacier", "Dhakuri"],
    gettingThere:
      "The Pindari trek starts at Kharkiya or Loharkhet, near Bageshwar, and takes about 5–6 days to Zero Point and back.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb("8/8b/Panwali_Dwar_and_Nanda_Khat.jpg"),
    credit: "Goutam1962",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=51771530",
    takenFrom: "Pindari Glacier trek",
    takenAt: "2011-04-08T08:49",
    camera: "Canon EOS 550D · 55 mm",
    coords: [30.064578, 79.909786],
  },
  {
    name: "Nanda Khat",
    elevation: 6611,
    district: "Bageshwar",
    region: "Kumaon Himalaya",
    summit: [30.301667, 79.975833],
    description:
      "Its long, flat summit ridge sits right above Zero Point, the end of the Pindari Glacier trek.",
    seeFrom: ["Pindari Glacier"],
    gettingThere:
      "The Pindari trek starts at Kharkiya or Loharkhet, near Bageshwar, and takes about 5–6 days to Zero Point and back.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb("0/00/Nandakhat.jpg"),
    credit: "Dhruvjoe",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=73483496",
    takenFrom: null,
    takenAt: "2010-06-18T08:57",
    camera: "Fujifilm FinePix S5700 · 15 mm",
    coords: null,
  },
  {
    name: "Nilkantha",
    elevation: 6596,
    district: "Chamoli",
    region: "Garhwal Himalaya",
    summit: [30.72, 79.4],
    description:
      "Rises straight above Badrinath. Be out in the temple town at sunrise to catch first light on its snow.",
    seeFrom: ["Badrinath"],
    gettingThere:
      "Badrinath is about 300 km by road from Rishikesh, via Joshimath. The road runs right into town.",
    bestTime: "May–Jun, Sep–Oct; the town is open roughly May–Nov",
    permit: "Free Char Dham yatra registration for the temple; none for the view",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Neelkanth.jpg",
    credit: "Alokprasad",
    license: "CC BY 3.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=7835094",
    takenFrom: null,
    takenAt: "2009-09-14T05:55",
    camera: "Fujifilm FinePix S5800 · 63 mm",
    coords: null,
  },
  {
    name: "Shivling",
    elevation: 6543,
    district: "Uttarkashi",
    region: "Gangotri Group",
    summit: [30.880411, 79.063469],
    description:
      "The granite spire that fills the sky above Tapovan, the meadow camp past Gaumukh at the end of the Gangotri trek.",
    seeFrom: ["Tapovan", "Gaumukh", "Bhojbasa"],
    gettingThere:
      "Drive to Gangotri, about 260 km from Rishikesh, then trek 18 km to Gaumukh. Tapovan is another 4 km up, across the glacier.",
    bestTime: "May–Jun, Sep–Oct; the park is closed in winter",
    permit: "Gangotri National Park permit from the forest office in Uttarkashi; Gaumukh is capped at 150 visitors a day",
    image: thumb(
      "0/00/Shivling_from_Nandanvan%2C_Mountain_peaks_of_Himalayas_Uttarakhand_India.jpg",
    ),
    credit: "Sharada Prasad CS",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=35429223",
    takenFrom: "Nandanvan, above the Gangotri Glacier",
    takenAt: "2014-08-23T09:12",
    camera: null,
    coords: [30.906011, 79.113138],
  },
  {
    name: "Changuch",
    elevation: 6322,
    district: "Pithoragarh / Bageshwar",
    region: "Kumaon Himalaya",
    summit: [30.29, 80.04],
    description:
      "Rises above the Pindari Glacier. Traill's Pass crosses its flank to the Milam side, a technical route for experienced climbers only.",
    seeFrom: ["Pindari Glacier"],
    gettingThere:
      "The Pindari trek starts at Kharkiya or Loharkhet, near Bageshwar, and takes about 5–6 days to Zero Point and back.",
    bestTime: "May–Jun, Sep–Oct",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb("8/8d/Changuch%2C_Uttarakhand%2C_India.jpg"),
    credit: "Yann",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=16952261",
    takenFrom: "Pindari Glacier trek",
    takenAt: "2011-09-30T08:10",
    camera: "Nikon Coolpix S3100 · 20 mm",
    coords: [30.25258, 79.995897],
  },
  {
    name: "Nanda Ghunti",
    elevation: 6309,
    district: "Chamoli",
    region: "Garhwal Himalaya",
    summit: [30.349444, 79.716111],
    description:
      "Shares the skyline with Trisul on the Brahmatal and Roopkund treks, and is the first big peak on the left from Ranikhet.",
    seeFrom: ["Brahmatal", "Lohajung", "Ranikhet"],
    gettingThere:
      "Lohajung, the trailhead for both treks, is a full day's drive from Kathgodam.",
    bestTime: "Dec–Mar for Brahmatal; May–Jun, Sep–Oct for Roopkund",
    permit: "Forest permit for the trek, usually arranged by the operator",
    image: thumb("a/a9/Nandaghunti_mountain.jpg"),
    credit: "Tatocha",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/w/index.php?curid=53157532",
    takenFrom: null,
    takenAt: "2016-10-17T12:13",
    camera: "Nikon Coolpix P610 · 39 mm",
    coords: null,
  },
];
